SELECT DISTINCT descricao 
FROM demonstracoes_contabeis 
WHERE UPPER(descricao) LIKE UPPER('%EVENTOS%SINISTROS%ASSISTÊNCIA%SAÚDE%')
   OR UPPER(descricao) LIKE UPPER('%EVENTOS%SINISTROS%ASSISTENCIA%SAUDE%')
   OR UPPER(descricao) LIKE UPPER('%EVENTOS%SINISTROS%MÉDICO%')
   OR UPPER(descricao) LIKE UPPER('%EVENTOS%SINISTROS%MEDICO%')
ORDER BY descricao; 